apiVersion: apps/v1
kind: Deployment

metadata:
  name: jeevanlink-deployment

spec:
  replicas: 3

  selector:
    matchLabels:
      app: jeevanlink

  template:
    metadata:
      labels:
        app: jeevanlink

    spec:
      containers:
        - name: jeevanlink-container
          image: neelapunani/jeevanlink

          ports:
            - containerPort: 3000

          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: jeevanlink-config
                  key: APP_ENV

            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: jeevanlink-config
                  key: APP_NAME

            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: jeevanlink-config
                  key: PORT

            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: jeevanlink-config
                  key: API_URL

---
apiVersion: v1
kind: Service

metadata:
  name: jeevanlink-service

spec:
  type: NodePort

  selector:
    app: jeevanlink

  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
