apiVersion: apps/v1

kind: Deployment

metadata:
  name: nginx
  labels:
    first: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80



    

# metadata:
#   name: web-app-deployment
#   labels:
#     app: web-app