apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}-deployment

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Values.labels.app }}

  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}

    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: "{{ .Values.container.image }}:{{ .Values.container.tag }}"

          imagePullPolicy: {{ .Values.container.pullPolicy }}

          ports:
            - containerPort: {{ .Values.container.port }}

          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: APP_ENV

            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: APP_NAME

            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: API_URL

            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: PORT

---
apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.service.name }}

spec:
  type: {{ .Values.service.type }}

  selector:
    app: {{ .Values.labels.app }}

  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}